### ISSUE TITLE
Size of the payload

### ISSUE THREAD

**Issue by Skyhikeeper** [RhynoVDS/ObjectTransport#12]
When i send a large object i get the following error

Unterminated string. Expected delimiter: ". Path 'Overview', line 1, position 65430.

Looks like a limit in the payload size.

Terence

**Comment by Skyhikeeper** [comment]
Looks like it is send the data from the server correctly, but it cannot decode the data on the client side,
This is the message generated from the server side, if I decode the JSON it works, I ahve got the message from a telnet client so this is the raw data been sent.

[Payload package.txt](https://github.com/RhynoVDS/ObjectTransport/files/2570959/Payload.package.txt)

**Comment by RhynoVDS** [comment]
Hi Skyhikeeper,

Thanks for raising this issue. Could you please send the class definition for "RemoteRecordClientData"? It will help me in my investigation.

Rhyno

**Comment by Skyhikeeper** [comment]
Hi Rhyno

 

This is the  class structure and it is defiantly the two byte array’s that are causing the issue, if I comment them out  the message goes through, I have also tested it using the datetime as a string it still does the same.

 

As mentioned before if I use telnet and check the data been sent from the server it is complete, only on the client side does it have an issue.

 

namespace RemoteData

{

    [Serializable]

    public class RemoteRecordClientData

    {

        public string Lane { get; set; }

        public int LaneNubmer { get; set; }

        public string Registration { get; set; }

        public byte[] PlatePatch { get; set; }

        public byte[] Overview { get; set; }

        public DateTime SightingDate { get; set; }

        public decimal Latitude { get; set; }

        public decimal Longitude { get; set; }

    }

}

 

 

Regards

Terence

**Comment by RhynoVDS** [comment]
Hi Terence,

I have found the issue and resolved it. Just running all unit tests and stabilising the solution. It should be good to go by the end of the week.

Regards,
Rhyno

**Comment by Skyhikeeper** [comment]
Hi Rhyno

 

Any news on the fix, I have to get some work out this weekend which requires the fix.


Terence

**Comment by RhynoVDS** [comment]
Hey Terence,

The fix has been pushed and ready. The TCP package has been updated.

Regards,
Rhyno

**Comment by Skyhikeeper** [comment]
Hi Rhyno


Will test today

 

Regards
Terence

**Comment by Skyhikeeper** [comment]
Hy Rhyno

{"Unterminated string. Expected delimiter: \". Path 'Overview', line 1, position 65430."}

Seem tha thte issue is still not resolved
